marksheetpro/urls.py
from django.contrib import admin
from django.urls import path
from marksheetapp.views import AddStudentView, AllStudentsView, AddStudentClassView, AddSubjectView, GetStudentsView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add_class', AddStudentClassView.as_view()),
    path('add_subject', AddSubjectView.as_view()),
    path('add_student/', AddStudentView.as_view(), name='add_student'), 
    path('all_student/', AllStudentsView.as_view(), name='marksheet'),
     path('getstudents/', GetStudentsView.as_view(), name='get-students'),
    
]

marksheetapp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

class StudentClass(models.Model):
    level = models.IntegerField(unique=True, validators=[MinValueValidator(1), MaxValueValidator(12)])

    def __str__(self):
        return str(self.level)

class Subject(models.Model):
    name = models.CharField(max_length=255)
    class_levels = models.ManyToManyField(StudentClass, related_name='subjects')

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=255)
    roll_no = models.CharField(max_length=20, unique=True)
    class_level = models.ForeignKey(StudentClass, on_delete=models.CASCADE)
    subjects = models.ManyToManyField(Subject, through='Score')
    image = models.ImageField(upload_to='student_images/', null=True, blank=True)

    def __str__(self):
        return self.name

class Score(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    score = models.IntegerField(null=True, blank=True, default=0        )

    def __str__(self):
        return f"{self.student.name} - {self.subject.name}: {self.score}"

marksheetapp/forms.py
from django import forms
from .models import Student, Subject, Score

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'roll_no', 'class_level', 'image']

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name']

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['subject', 'score']
    
StudentFormSet = forms.formset_factory(ScoreForm, extra=5)

marksheetapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from rest_framework import generics
from .forms import StudentForm, SubjectForm, StudentFormSet
from .models import Student, Subject, Score
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .serializers import StudentClassSerializer, SubjectSerializer, StudentSerializer, ScoreSerializer
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from django.db.models import Sum, Count

class AddStudentClassView(generics.CreateAPIView):
    serializer_class = StudentClassSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
    
class AddSubjectView(generics.CreateAPIView):
    serializer_class = SubjectSerializer

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

class AddStudentView(View):
    template_name = 'add_student.html'

    def get(self, request):
        student_form = StudentForm()
        subject_form = SubjectForm()
        score_formset = StudentFormSet(prefix='scores')
        return render(request, self.template_name, {
            'student_form': student_form,
            'subject_form': subject_form,
            'score_formset': score_formset,
        })

    def post(self, request):
        student_form = StudentForm(request.POST, request.FILES)
        subject_form = SubjectForm(request.POST)
        score_formset = StudentFormSet(request.POST, prefix='scores')

        if student_form.is_valid() and subject_form.is_valid() and all(form.is_valid() for form in score_formset):
            student = student_form.save(commit=False)
            student.save()

            class_level = student.class_level
            selected_subjects = subject_form.cleaned_data.get('subjects', [])
            selected_scores = [(form.cleaned_data['subject'], form.cleaned_data['score']) for form in score_formset]

            student.subjects.clear()

            for subject in set(selected_subjects):
                student.subjects.add(subject)

            for subject, score_value in selected_scores:
                Score.objects.create(student=student, subject=subject, score=score_value)

            return redirect('add_student')

        return render(request, self.template_name, {
            'student_form': student_form,
            'subject_form': subject_form,
            'score_formset': score_formset,
        })
    
class AllStudentsView(View):
    template_name = 'all_students.html'
    items_per_page = 10

    def get(self, request):
        sort_by = request.GET.get('sort_by', 'name')
        sortable_columns = {'name', 'roll_no', 'total_score'}

        if sort_by not in sortable_columns:
            sort_by = 'name'
        students = Student.objects.annotate(total_score=Count('score')).order_by(sort_by)
        paginator = Paginator(students, self.items_per_page)
        page = request.GET.get('page', 1)

        try:
            students_paginated = paginator.page(page)
        except PageNotAnInteger:
            students_paginated = paginator.page(1)
        except EmptyPage:
            students_paginated = paginator.page(paginator.num_pages)
        return render(request, self.template_name, {'students': students_paginated, 'sort_by': sort_by})
    
class GetStudentsView(generics.ListAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = StudentSerializer

    def get_queryset(self):
        queryset = Student.objects.annotate(
            total_score=Sum('score__score')
        ).order_by('-total_score')

        class_level = self.request.query_params.get('class')
        if class_level:
            queryset = queryset.filter(class_level__level=class_level)

        return queryset

marksheetapp/templates/add_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Marksheet</title>
</head>
<body>
    <h1>Student Marksheet</h1>
    <form method="post" enctype="multipart/form-data" id="studentForm">
        {% csrf_token %}
        {{ student_form.as_p }}
        {{ score_formset.management_form }}
        {% for form in score_formset %}
            {{ form.as_table }}
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

    <table>
        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.name }}</td>
                    <td>{{ student.roll_no }}</td>
                    <td>{{ student.class_level }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="pagination">
        <span class="step-links">
            {% if students.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ students.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ students.number }} of {{ students.paginator.num_pages }}.
            </span>

            {% if students.has_next %}
                <a href="?page={{ students.next_page_number }}">next</a>
                <a href="?page={{ students.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>

marksheetapp/templates/all_students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Students Data</title>
</head>
<body>
    <h1>All Students Data</h1>

    <table border="1">
        <thead>
            <tr>
                <th><a href="?sort_by=name">Student Name</a></th>
                <th><a href="?sort_by=roll_no">Roll No</a></th>
                <th><a href="?sort_by=class_level">Class Level</a></th>
                <th>Subjects</th>
                <th>Scores</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
                <tr>
                    <td>{{ student.name }}</td>
                    <td>{{ student.roll_no }}</td>
                    <td>{{ student.class_level }}</td>
                    <td>
                        {% for subject in student.subjects.all %}
                            {{ subject.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for score in student.score_set.all %}
                            {{ score.score }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Pagination links -->
    <div class="pagination">
        <span class="step-links">
            {% if students.has_previous %}
                <a href="?page=1{% if sort_by %}&sort_by={{ sort_by }}{% endif %}">&laquo; first</a>
                <a href="?page={{ students.previous_page_number }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ students.number }} of {{ students.paginator.num_pages }}.
            </span>

            {% if students.has_next %}
                <a href="?page={{ students.next_page_number }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}">next</a>
                <a href="?page={{ students.paginator.num_pages }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>